development:
  adapter: mysql2
  encoding: utf8
  database: blog_development
  username: root
  password: ""
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: blog_test
  username: root
  password: ""
  host: localhost
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  database: blog_production
  username: root
  password: ""
  host: localhost
  port: 3306


